### ISSUE TITLE
Fuel Enhancement 

### ISSUE THREAD

**Issue by BickleBuice** [VolmitSoftware/VehiclesPlus#45]
**Is your enhancement related to a problem? Please describe.**  Yes, I am unable to use fuel that players actually work to create and trade and am forced to make them throw money out of the economy using a GUI for fuel 
A clear and concise description of what the problem is.
I’m very frustrated by the fact I got a entire custom plugin that lets you extract oil from the ground, refine it make gasoline and gas cans and can’t even use them to fuel vehicles 
**Describe the solution you'd like**  

Allow in config to put custom fuel types, that do not need to be bought through the command, and you should be able to set it as any item, so for a example if it’s set people would be able to use coal they mine as fuel or wood etc, or in my case gas cans that were produced and manufactured in order to fuel vehicles 

**Additional context**  

I feel this will just make the plugin 10x better making it much more adaptable to servers, and make the plugin feel more complete.

**Comment by Collinvh** [comment]
You could create a crafting recipe for fuel

**Comment by relavis** [comment]
This is already how the plugin works.
