### ISSUE TITLE
Some ideas that i have for this plugin

### ISSUE THREAD

**Issue by Perrosovietico** [VolmitSoftware/VehiclesPlus#49]
**Is your feature request related to a problem? Please describe.**  
I have no problems.

**Describe alternatives you've considered**  
- A setting option in which only the owner of his vehicle can drive it, when you unlock a vehicle, everyone can use the driver seat, i have this idea to prevent vehicle stealing from another players.

- Delete vehicle command. Instead of the command '/vehicle give (player) (vehiclename) R G B', it would be nice if you add a command that deletes the vehicle from a player's garage, for example '/vehicle delete (player) (vehiclename)', i'm doing a roleplay server where there are jobs, I want to make sure that when someone leaves their job, their vehicle is eliminated.

**Additional context**  
I don't have additional context

**Comment by relavis** [comment]
The locking system is meant to allow vehicle owners to lock their own cars, just like real life. They can lock their car as needed.

We've added vehicle-based permissions now, so your second suggestion can now use the `vp.ride.<Type>` permissions.
