### ISSUE TITLE
Modify the GUI & more

### ISSUE THREAD

**Issue by Serial23** [VolmitSoftware/VehiclesPlus#53]
**Is your feature request related to a problem? Please describe.**
I have no problems.

**Describe alternatives you've considered**

The possibility to modify the gui of garage, I mean the items to display and what display, for example i don't want that players can buy the upgrades so i want to remove it from the gui, also for the item to display, for example i don't want display an oak door for "Enter vehicle", so i want a config with these options, for modify the items also the custom-model-data

**Additional context**
I don't have additional context

**Comment by relavis** [comment]
Duplicate of #46
