### ISSUE TITLE
NullPointerException in CollisionManager

### ISSUE THREAD

**Issue by notFallingDevil** [VolmitSoftware/VehiclesPlus#55]
**Describe the bug**  
https://mclo.gs/ChW6nu6
It does not crash the server but it removes car from like the world. It's still in the garage.

**To Reproduce**  
1. Take a car (this bug mostly comes while using our BMW, here's that car config: https://pastebin.pl/view/27814803)
2. Ride maximum speed (100 km/h)
3. Car dissapears
4. Check logs

**Expected behavior**  
I espected the car not to dissapear.

**Screenshots or Video Recordings**  
Just logs: https://mclo.gs/ChW6nu6

**Server and Plugin Information**  
 - Installed plugins: Too many to write them down
 - VehiclesPlus Version: VehiclesPlusPro v2.0.10-dev4
 - Pro or Lite?: Pro
 - Server Platform and Version: Mohist 1.12.2
 - Operating System (if applicable): Debian / Ubuntu

**Additional context**  
Add any other context about the problem here, server timings reports, complete console log etc. Please do not make Pastebin dumps or screenshot expire.
Omg sorry for giving pastebin config but it's only for copy so i think it should be good yes?

**Comment by relavis** [comment]
Please try newest versions and confirm that the bug still exists.
