### ISSUE TITLE
NullPointerException: null Error

### ISSUE THREAD

**Issue by WalrusSlayer** [VolmitSoftware/VehiclesPlus#56]
**Describe the bug**  
Doesn't seem to do anything but spam console.

**To Reproduce**  
1. Startup Server
2. Error:
`

  | [03:56:35 WARN]: [VehiclesPlusPro] Task #18221 for VehiclesPlusPro v2.1.0-dev4 generated an exception
-- | --
  | java.lang.NullPointerException: null
  | at me.legofreak107.vehiclesplus.vehicles.vehicles.objects.StorageVehicle.loadFromStorage(StorageVehicle.java:158) ~[?:?]
  | at me.legofreak107.vehiclesplus.vehicles.managers.MainManager.loadVehicles(MainManager.java:282) ~[?:?]
  | at me.legofreak107.vehiclesplus.vehicles.listeners.PlayerJoin$1.run(PlayerJoin.java:22) ~[?:?]
  | at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-414]
  | at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-414]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.4.jar:git-Paper-414]
  | at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-414]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-414]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-414]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-414]
  | at java.lang.Thread.run(Thread.java:834) [?:?]

`

**Expected behavior**  
No idea what it does. Game seemingly works fine, but it spams console.

**Server and Plugin Information**
 - Installed plugins: ![image](https://user-images.githubusercontent.com/40503028/105151954-96881780-5ad4-11eb-9819-e7481999d89d.png)
 - Version: 2.0.10
 - VehiclesPlus Version: Pro
 - Server Platform and Version: PaperSpigot 1.16.4 #416
 - Operating System (if applicable): Server Host

**Additional context**  
Timings Report:
https://timings.aikar.co/?id=5931da5e8e504c7fbb46a5375484853c

**Comment by stijnb1234** [comment]
Did you add vehicles yourself, or do you use the default vehicles?

**Comment by WalrusSlayer** [comment]
> Did you add vehicles yourself, or do you use the default vehicles?

Default

**Comment by WalrusSlayer** [comment]
https://download.mc-packs.net/pack/f6fba886951c767c3de06f4c9c68fa877c8daaba.zip

Is the link. If it helps to take a look at it, particularly sounds.json.

**Comment by stijnb1234** [comment]
Remove your `data` folder. It contains a corrupted vehicle.

**Comment by relavis** [comment]
Please reopen if you still need support.
