### ISSUE TITLE
forceshop not working

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#60]
**Describe the bug**  
When you try to run forceshop on a player it doesnt work and opens the gui for yourself, it also does not work for command blocks.
**To Reproduce**  
1. Go to 'ur server'
2. run the /v forceshop (user)
3. it displays the shop for yourself but not the other user
4. In command block you get "Error console may not execute this command"

**Expected behavior**  
I expected it to open it for the player
**Server and Plugin Information**
 - Installed plugins: way to many to list.
 - VehiclesPlus Version: latest
 - Pro or Lite? pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: purpur 1.16.5

**Comment by relavis** [comment]
Will be fixed in 2.2.5
