### ISSUE TITLE
REQUEST: Better tuning

### ISSUE THREAD

**Issue by notFallingDevil** [VolmitSoftware/VehiclesPlus#64]
**Is your feature request related to a problem? Please describe.**  
I'm flustrated with that how tuning works now, it was better in vpro v1.

**Describe the solution you'd like**  
Tuning excatly the same as in vpro v1.

**Describe alternatives you've considered**  
NONE

**Additional context**  
Tuning in newest vpro su*ks.

**Comment by relavis** [comment]
I have no idea how tuning used to work. I do not have the original source code nor do I have access to the original jars. You'll have to be more specific.

**Comment by stijnb1234** [comment]
@notFallingDevil On which point did you liked the tuning that is missing now? All the options are the same, so you are not missing any configuration options.

**Comment by relavis** [comment]
Closing as they haven't responded.
