### ISSUE TITLE
Planes despawn randomly

### ISSUE THREAD

**Issue by uTogglin** [VolmitSoftware/VehiclesPlus#65]
Plane despawns for no resson
use protocol lib latest dev build on 1.16.5 

the plugin to be usable   

**Screenshots or Video Recordings**  
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Information*
only plugin aside from vault and protocol lib 
 - VehiclesPlus Version: latest
 - Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]:
 - spigot 1.16.5
 - ubuntu 18.05

**Comment by relavis** [comment]
Have you pregenerated your world?

**Comment by uTogglin** [comment]
yes and tried lowering speed

**Comment by stijnb1234** [comment]
Can you record the despawning? We need more information to check what's wrong.

**Comment by uTogglin** [comment]
I have  deleted the server give me a while to set it back up

**Comment by relavis** [comment]
Please reopen when you are ready.
