### ISSUE TITLE
Bug, Bike glitches.

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#67]
**Describe the bug**  
When one jumps off a bike it doesn't allow them to go back on the bike and for some reason it doesn't fully process the server was on the bike in the first place.

**To Reproduce**  
1. Go to a bike
2.  drive a few blocks
3.  hop off
4. try to get back on bike
**Expected behavior**

**Comment by relavis** [comment]
Unable to reproduce, this is likely because you are using Purpur which is not supported.
