### ISSUE TITLE
Fuel not working

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#68]
**Describe the bug**  
Fuel is not working when trying to spawn it in and its not clear how to fuel cars.

**To Reproduce**  
1. Spawn a car
2. Drive it untill fuel goes down
3. Try to spawn in fuel (doesnt work)
4. Try to find how to fuel a car(unclear)

**Expected behavior**  
It is expected that you can spawn in fuel and then fuel the car either through the gui or right clicking the car with fuel.

**Comment by relavis** [comment]
Can you be more clear on how you can't spawn in fuel?

Also, please include the "Server and Plugin Information" tab of your issue reports, I need that information to diagnose.

**Comment by relavis** [comment]
Closing until you respond.
