### ISSUE TITLE
Bug "Vehicle is occupied"

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#69]
**Describe the bug**  
When a car is force despawned or crashed sometimes when respawning one when trying to enter the drivers seat you get "vehicle is occupied"

**To Reproduce**  
1. SPawn a car
2. drive it
3. force despawn it

**Expected behavior**  
You can reenter the vehicle as normal.

**Comment by relavis** [comment]
Fixed in 2.2.5
