### ISSUE TITLE
Console spam when driving/in vehicle

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#70]
**Describe the bug**  
When you enter the vehicle console is instantly spammed.

**To Reproduce**  
1. Enter vehicle

**Expected behavior**  
Errors to not be spammed in console.

**Screenshots or Video Recordings**  
https://pastebin.com/e4RvrSLk

**Server and Plugin Information**
 - Installed plugins: A bit to many to show
 - VehiclesPlus Version: 2.2.4
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: Purpur/Waterfall 1.16.5
 - Operating System (if applicable): Java  11

**Comment by relavis** [comment]
Purpur is currently not supported by VehiclesPlus.
