### ISSUE TITLE
Make cars spawn locked.

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#71]
**Is your enhancement related to a problem? Please describe.**  
It's always annoying when cars auto spawn unlocked and steal able so i was hoping a auto lock config was added.

**Describe the solution you'd like**  
A config that locks all vehicles when spawned and only unlock when manually done. Along with a command to trust a specific player to your vehicle so its not public or private no inbetween.

**Additional context**

**Comment by stijnb1234** [comment]
I think it's a good idea to add a config option for it. I personally do believe that the default value should be unlocked, because you don't buy the car locked at a car dealership either. :P

**Comment by relavis** [comment]
Will be added in 2.2.6
