### ISSUE TITLE
New feature for Vehicles

### ISSUE THREAD

**Issue by RollexGrief** [VolmitSoftware/VehiclesPlus#74]
This is not a problem for the plugin, but I want the vehicles not to disappear after the player leaves. 

I want the vehicles not to disappear after the player leaves, so that you can create a transport WITHOUT OWNER and work correctly after reloading. 

There should be alternatives ...

**Comment by relavis** [comment]
This can't be added due to the immense amount of entity lag that it introduces.

**Comment by RollexGrief** [comment]
So players won't see this feature in the future?
