### ISSUE TITLE
Custom Data Fuel not working.

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#76]
**Describe the bug**  
Custom model data within fuel is not working even though it is meant to be supported in item stacker.

**To Reproduce**  
1. Go to 'config'
2. Click on 'fuels'
3. Scroll down to 'Gaslone'
4. Add custom-model-data: (according to item stack serialization https://www.spigotmc.org/wiki/itemstack-serialization/) 
5. See error of it not working

**Expected behavior**  
I expected it to adopt the custom model data.

**Screenshots or Video Recordings**  
https://cdn.discordapp.com/attachments/803151967442567178/814059418244481054/unknown.png

**Server and Plugin Information**
 - Installed plugins: a lot, not really easy to specify.
 - VehiclesPlus Version: 2.2.5 i believe (latest version)
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: Paper Spigot 1.16.5
 - Operating System (if applicable): Java 11

**Additional context**  
Add any other context about the problem here, server timings reports, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by relavis** [comment]
Tested on 2.2.7 and is working.
Make sure you include the meta tags.
`className: me.legofreak107.vehiclesplus.vehicles.fuel.FuelType
name: Gasoline
pricePerLiter: 1.5
fuelItem:
  ==: org.bukkit.inventory.ItemStack
  v: 2586
  type: IRON_INGOT
  meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      custom-model-data: 1234567`
