### ISSUE TITLE
Allow hand models for vehicles.

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#81]
**Is your enhancement related to a problem? Please describe.**  
A major issue with this plugin is glitching regarding multi model vehicles. Especially helicopters and airplanes. They are extremely buggy and I do realize they will be difficult to fix so I believe that this may be a short and temporary solution allowing usage of bigger models because hand models can be 12x12x12 and the way it is now is limited to 7x7x7.

**Describe the solution you'd like**  
Allow a player to specify if they want the model to be a hand model instead of what it currently is. This is a very important thing to me and I'd willing to pay in order for it to be prioritized.

**Additional context**

**Comment by relavis** [comment]
Will be added in 2.3.0.
