### ISSUE TITLE
Spawning vehicles from your garage.

### ISSUE THREAD

**Issue by Pvmdark** [VolmitSoftware/VehiclesPlus#88]
**The problem is that you can spawn your vehicle anytime except if it's broken.** 
Basically you can instant spawn your car and drive with it and pick it up, then you can go in a building and if you're back on the streets you can spawn it again. People can't destroy your car in that case.

**The solution**  
You could add a pay per spawn feature or/and a cooldown on spawning/picking up a vehicle. 

**Alternative/extra solution**  
You could also make a cooldown on the arriving of the vehicle.

**Comment by stijnb1234** [comment]
Duplicate of #84

**Comment by SatireShadow** [comment]
I can offer you a few alternatives to this if you message me on discord Rusty#0001.
